project:
  name: pap
  version: 0.1.0-beta

# stage tree chart: https://statik.munchii.me/img/:f5e35ec9-faea-4637-81eb-b677a6a81a4b
stages:
  stage1:
    name: Stage 1
    trigger:
      stage:
        - id: stage1-retry
          when: complete
    flow:
      steps:
        - name: Build
          run: dub build --compiler=ldc2 -b release

  stage1-retry:
    name: Stage 1 Retry
    trigger:
      stage:
        - id: stage1
          when: failed
    flow:
      steps:
        - name: Retry Stage 1
          run: echo "Retrying Stage 1..."
          
  stage2:
    name: Stage 2
    trigger:
      stage:
        - id: stage1
          when: started
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage3:
    name: Stage 3
    trigger:
      stage:
        - id: stage1
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage4:
    name: Stage 4
    trigger:
      stage:
        - id: stage1
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage5:
    name: Stage 5
    trigger:
      stage:
        - id: stage2
          when: started
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage6:
    name: Stage 6
    trigger:
      stage:
        - id: stage2
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage7:
    name: Stage 7
    trigger:
      stage:
        - id: stage2
          when: failed
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage8:
    name: Stage 8
    trigger:
      stage:
        - id: stage3
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage9:
    name: Stage 9
    trigger:
      stage:
        - id: stage3
          when: skipped
        - id: stage4
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage10:
    name: Stage 10
    trigger:
      stage:
        - id: stage5
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage11:
    name: Stage 11
    trigger:
      stage:
        - id: stage8
          when: skipped
        - id: stage9
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."
          
  stage12:
    name: Stage 12
    trigger:
      stage:
        - id: stage6
          when: complete
        - id: stage7
          when: complete
        - id: stage10
          when: complete
        - id: stage11
          when: complete
    flow:
      steps:
        - name: Do something
          run: echo "doing something..."